repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]
    stages: [pre-commit, pre-merge-commit, pre-push, manual]
    args: ['--filter-files']
    require_serial: true
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
    require_serial: true
  - id: bandit
    name: bandit
    entry: bandit
    language: system
    types: [python]
    require_serial: true
