name: Publish Python distribution to PyPI

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"  
    - name: Install dev tools
      run: python -m pip install build pytest
    - name: Test with pytest
      run: pytest .
    - name: Build a binary wheel and a source tarball
      run: python -m build
